### ISSUE TITLE
Several Duplicates

### ISSUE THREAD

**Issue by huths0lo** [helium/angry-purple-tiger#5]
One of the tests is supposed to point out if any dupes exist.  There are a number of them.

skinny
short
long
cool
hot
tangy
tiger (in colors and animals)
swift (in animals and adjectives)
mammoth (in animals and adjectives)
raccoon

**Comment by huths0lo** [comment]
Removed the duplicate of the duplicate short :)

**Comment by madninja** [comment]
Unfortunately duplicates in the word lists can not be removed since that would affect the names that are generated. i.e. previously generated names would no longer be generated for the same key if we modify the world lists.
