### ISSUE TITLE
Duplicate attribute and animal entries

### ISSUE THREAD

**Issue by sunsided** [helium/angry-purple-tiger#6]
The adjectives list contains duplicates of the words `skinny`, `short`, `long`, `cool`, `hot` and `tangy`.
The animal list contains duplicates of the word `tiger`, `mammoth` and `raccoon`.
The word `swift` is used both as an adjective and animal name.

It seems like the `wordlists` test `should contain no duplicate entries` should have caught this but it checks only against the original list lengths rather than the actual `wordcount` tally keys:

https://github.com/helium/angry-purple-tiger/blob/9c78963bd13cf5ae585dfbb07c5e5c029e7f0965/test/index.js#L46-L59

Other (derived?) implementations such as [angry-purple-tiger-rs](https://github.com/helium/angry-purple-tiger-rs) and [erl_angry_purple_tiger](https://github.com/helium/erl_angry_purple_tiger) have the same issue.

**Comment by madninja** [comment]
Indeed they do. Unfortunately this can not be fixed since it would break existing names for folks. i.e.if we fix the list your hotspot would suddenly change names.
